### ISSUE TITLE
Can you guys make the Escape/Pause Menu Togglable?

### ISSUE THREAD

**Issue by unknowlence** [DeeChael/HoYoI#5]
Some might prefer having the default escape/pause menu and keep the loading screen that the mod provides.

So a toggle in the mod settings would be nice..
That's just a suggestion, Thank you!

**Comment by DeeChael** [comment]
This is mentioned in #2 actually and my anwser is yes but not now because im still working on other features and when those features are finished, config will be added.

**Comment by DeeChael** [comment]
done in 0.0.3-beta
